### ISSUE TITLE
gruntfile-gtx needs a new owner

### ISSUE THREAD

**Issue by Bartvds** [Bartvds/gruntfile-gtx#19]
If you are using this package and want to take ownership to upgrade or extend then please contact me through regular email and we can arrange transfer of the github repos and npm ownership.

If you just want to push a new version then that can be arranged as well.

My only requirements are you have some npm or github credibility and a pledge to be a better and more persistent steward then I was. Of course github, npm and community rules also apply.

**Comment by killmenot** [comment]
Hi @Bartvds,

I sent you email about ownership but haven't got an answer. Could you please consider my candidature?

**Comment by killmenot** [comment]
@Bartvds Hey, are you still interesting in someone to take an ownership?

**Comment by killmenot** [comment]
Thank you

**Comment by Bartvds** [comment]
Thanks for asking :)
